### PR TITLE
Extractor Catalog: Job History features

### PR DESCRIPTION
**Pull request by bodom0015**
## Description
This PR adds a "Job History" view to the Extractor Catalog.

NOTE: It is still unclear whether this view will be eventually separated from the proposed "Metrics" view. 

### Problem
While we can view all extraction events for a given dataset or file, we do not have a way to view the entire job history for a given extractor.

### Approach
* Add the Extractor Job History view / route
* Link off to Job History view from Extractor Catalog
* Refactor existing job history view / grouping code to reuse as much as possible

### How to Test
Prerequisites: RabbitMQ plugin enabled, at least one extractor registered

1. Checkout and run this branch locally
2. Login to Clowder
3. Navigate to the Explore > Extractors view
4. Beside an extractor, expand the dropdown menu and choose "View History"
    * You should be taken to the new Job History view
    * The view should look very similar to the Extractions tab, displayed below files and datasets
    * You should see all jobs that have run by this extractor are listed here
    * You should be able to click a job to expand it and see the individual events from that job
5. Verify that the Extractions tab below files/datasets still appears and functions as intended

## Review Time Estimate

- [ ] Immediately
- [x] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lmarini** [comment]
I am getting an error rendering the /extractors page. Trying to see if there is something different about my database, but I thought I would put this here while I investigate in case you have any ideas of what might have changed that would result in this error. The `extractor-catalog-wireframe` works fine with my current database.

```
! @7h9og9b5h - Internal server error, for (GET) [/clowder/extractors] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: key not found: ncsa.tensorflow.mnist]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:170) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:167) [play_2.10-2.2.6.jar:2.2.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.util.NoSuchElementException: key not found: ncsa.tensorflow.mnist
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:58) ~[scala-library.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[scala-library.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:58) ~[scala-library.jar:na]
	at views.html.updateExtractors$$anonfun$apply$1$$anonfun$apply$2.apply(updateExtractors.template.scala:218) ~[classes/:na]
	at views.html.updateExtractors$$anonfun$apply$1$$anonfun$apply$2.apply(updateExtractors.template.scala:183) ~[classes/:na]
```

**Comment by bodom0015** [comment]
I have not seen that error before.. the only part of the `/extractors` view that should have changed was the addition of the following for displaying the Job Counts:
```
@groups(extractor.name).allMsgs.keySet.size
```

I think that `ExtractionService.groupByType` in your case does not contain a complete mapping for all of your extractors. I'm not sure why this would occur... perhaps this indicates another backwards compatibility issue?

I am not sure how to recreate this test case, but I could try adding the following NullObject pattern to the return value of `groupByType` if you think it might help:
```
groupings.withDefaultValue(ExtractionGroup("N / A", "N / A", "N / A", Map()))
```

This way, any missing extractors wouldn't throw `key not found`, they would simply return a default value that would likely display "N / A"

**Comment by max-zilla** [comment]
I got a similar error switching to this branch from your extractor-catalog-wireframe branch that worked:

```
@7ha4b5d3b: Execution exception in /Users/mburnette/Git/clowder/app/views/updateExtractors.scala.html:194
...
Caused by: java.util.NoSuchElementException: key not found: opendronemap.stitcher
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
...
```

I added your suggested line to MongoDBExtractionService.groupByType (return groupings.withDefaultValue) and that fixed the issue, the job history for that extractor is blank but that is to be expected i think. will try running some extractors through it soon.

Want me to push the changed line?

**Comment by bodom0015** [comment]
@max-zilla I think it's ok that its blank, since it seems like the error stems from the db not having any of these Extraction events available? Sadly I don't have a similar db state to work against, but if you're confident that this worked around the issue then please do push the changed line.

Normally I would have "suggested " a commit on the PR here, but I can't seem to do that because `groupByType` didn't change as a part of this PR

**Comment by lmarini** [comment]
I can confirm that fixes the error for me as well. Thank you.

**Review by lmarini — APPROVED** [review]

**Comment by lmarini** [comment]
Looks good to me. @bodom0015 can you resolve the conflicts and merge it? Thank you.

**Pull request merged**
