### PR TITLE
Added an IFC previewer and a GLTF previewer

### PR DESCRIPTION
**Pull request by cconsta1**
## Description

I implemented an IFC previewer and added GLTF loading capabilities to the `three_js` previewer

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [X] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the CHANGELOG.md.
- [X] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cconsta1** [comment]
I found an IFC file for testing [here](https://github.com/mrdoob/three.js/tree/dev/examples/models/ifc) and GLTF files can be found [here](https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf).

**Comment by cconsta1** [comment]
Hi @lmarini,

I got a new machine and when I made the first commit, my local `git` on my machine was not linked to my email account yet. I did that after I made my first commit, that's why the only thing that appears in the first commit is my name (Chrysovalantis Constantinou), whereas with the second and third commits my regular username `cconsta1` appears. Is there a way around this? Or shall I close this pr and open a new one?

**Comment by lmarini** [comment]
> Hi @lmarini,
> 
> I got a new machine and when I made the first commit, my local `git` on my machine was not linked to my email account yet. I did that after I made my first commit, that's why the only thing that appears in the first commit is my name (Chrysovalantis Constantinou), whereas with the second and third commits my regular username `cconsta1` appears. Is there a way around this? Or shall I close this pr and open a new one?

That's fine. Thanks for the clarification. Since there isn't another email/account specified, I think we good.

**Comment by cconsta1** [comment]
@lmarini, that's cool then! I also changed the mimetypes by adding `model/ifc`, `model/IFC`. I hope things work and thanks!

**Review by lmarini — APPROVED** [review]
Both worked well. Thank you!

**Pull request merged**
