### PR TITLE
Allow sorting by metadata fields

### PR DESCRIPTION
**Pull request by max-zilla**
Adds "sort" and "order" parameters for search api, with swagger entries. Support for date and numeric fields. I have implementation of "name" with a _sort field but not mentioned in documentation because other strings not yet supported - wanted to include this code as a working example.

Also included is a new /api/deleteindex endpoint for easier reindexing on sharded instances.

### CODE REVIEW

**Review by bodom0015 — CHANGES_REQUESTED** [review]
Indentation issue breaks the Swagger API browser. The lack of string support made things a bit confusing, so we may want to return/handle a different error code here (maybe 405 - Method Not Allowed).

In general, the date sorting seemed to work (although, in my case I didn't have any numeric values to sort with)

I also thought it was strange that the `/search` endpoint doesn't seem to handle errors very well. The Swagger API was returning a strange error that I had never seen before when trying to search on "name" (which you had indicated wouldn't work):
```
Undocumented | Failed to fetch.
Possible Reasons:
* CORS
* Network Failure
* URL scheme must be "http" or "https" for CORS request
```

An exception was thrown in IntelliJ too:
```
play.api.Application$$anon$1: Execution exception[[SearchPhaseExecutionException: all shards failed]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:170) [play_2.10-2.2.6.jar:2.2.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:167) [play_2.10-2.2.6.jar:2.2.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389) ~[elasticsearch-2.3.5.jar:2.3.5]
Caused by: org.elasticsearch.search.SearchParseException: No mapping found for [name._sort] in order to sort on
	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667) ~[elasticsearch-2.3.5.jar:2.3.5]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633) ~[elasticsearch-2.3.5.jar:2.3.5]
```

We should probably handle this exception more gracefully and return an HTTP error code

**Comment by max-zilla** [comment]
Thanks @bodom0015 , merged your changes and looking into error. I am getting error looking at Swagger as well:

 ```Parser error on line 24
can not read a block mapping entry; a multiline key may not be an implicit key```
however, this PR doesn't change that line and i get same error on develop branch. investigating.

**Comment by max-zilla** [comment]
Also updated PR to omit the name._sort autofill until it's properly supported, that way databases that haven't been reindexed don't throw errors.

**Review by bodom0015 — APPROVED** [review]
LGTM :+1: Thank you, @max-zilla!

**Pull request merged**
