### PR TITLE
fix to rabbitmq

### PR DESCRIPTION
**Pull request by robkooper**
- personal spaces would crash an upload
- images now pushed to ghcr.io

## Review Time Estimate

- [X] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by robkooper** [comment]
would like to get 2 more things fixed
- no parameters for extractor in submission page throws error in console.
- error when receiving message from extractor in rabbitmq plugin.

**Comment by robkooper** [comment]
```
[ERROR] [11/06/2020 04:08:47.270] [application-akka.actor.default-dispatcher-3] [akka://application/user/EventFilter] JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
 play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
 at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:64)
 at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:64)
 at play.api.libs.json.JsResult$class.fold(JsResult.scala:71)
 at play.api.libs.json.JsError.fold(JsResult.scala:10)
 at play.api.libs.json.JsValue$class.as(JsValue.scala:62)
 at play.api.libs.json.JsUndefined.as(JsValue.scala:94)
 at services.EventFilter$$anonfun$receive$3.applyOrElse(RabbitmqPlugin.scala:1208)
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
 at akka.actor.ActorCell.invoke(ActorCell.scala:456)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
 at akka.dispatch.Mailbox.run(Mailbox.scala:219)
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
 at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by robkooper** [comment]
need to check this on an empty space that has never had extractors enabled in it.

**Review by lmarini — APPROVED** [review]
Can confirm that the submission bug doesn't happen for datasets not in a space and happens for those in a space. This fixes it.

**Pull request merged**
