### PR TITLE
File "CREATED" status should prevent user download / notify user why they can't download

### PR DESCRIPTION
**Pull request by bodom0015**
### Problem
Download button is already active for files that are CREATED, but not PROCESSED.

### Approach
* When file status is `CREATED`, disable the Download button and displays a tooltip saying we need to wait
* When file status is `CREATED`, show a banner indicating that file bytes aren't available but metadata and comments are

### How to Test
1. Checkout and run this branch locally
2. Login to Clowder
3. Create a dataset, if you haven't already
4. Upload a file, if you haven't already
5. Exec into `mongo` container: `docker exec -it mongo bash`
6. Within the mongo container, launch the mongo shell: `mongo`
7. Manually set the file's status to `CREATED` - NOTE: this effectively simulates an in-transit file
```python
MongoDB shell version v3.4.17
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.17
Server has startup warnings: 
2021-02-17T20:48:34.934+0000 I CONTROL  [initandlisten] 
2021-02-17T20:48:34.934+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-02-17T20:48:34.934+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-02-17T20:48:34.934+0000 I CONTROL  [initandlisten] 
> use clowder
switched to db clowder
> db.uploads.findOne({ '_id': ObjectId("602d8d63d72896ee1491a1ff") })
{
	"_id" : ObjectId("602d8d63d72896ee1491a1ff"),
	"_typeHint" : "models.File",
	...
	"status" : "PROCESSED"
}
> db.uploads.updateOne({ '_id': ObjectId("602d8d63d72896ee1491a1ff") }, { '$set': { "status": "PROCESSED" }})
{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
> db.uploads.findOne({ '_id': ObjectId("602d8d63d72896ee1491a1ff") })
{
	"_id" : ObjectId("602d8d63d72896ee1491a1ff"),
	"_typeHint" : "models.File",
	...
	"status" : "CREATED"
}
```
6. Navigate to the file in Clowder: http://localhost:9000/files/602d8d63d72896ee1491a1ff
    * You should see the Download button is disabled
    * You should see a tooltip when hovering to mouse cursor over the Download button
    * You should see a warning banner notifying the user that the bytes for this file are not yet available

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by max-zilla** [comment]
This works on the file page, but on the dataset view the file is still available for download. (it even works, since I just cheated in the db and overrode status) Is it possible to check status on dataset page?

Screen Shot 2021-02-23 at 1 36 28 PM

Screen Shot 2021-02-23 at 1 36 34 PM

**Comment by tcnichol** [comment]
As per Max's find, I also checked with a file in a folder. The user can still download a file if it's in a folder when status=CREATED.

**Comment by bodom0015** [comment]
@max-zilla @tcnichol Good catch on these two cases! I hadn't considered just how many ways there are to download a file...

This also brings up an interesting edge case for other methods:
* What happens if a user downloads an entire dataset (or collection or folder or selection) that contains one or more files that are either CREATED or ARCHIVED? Currently, we won't be able to reliably provide the file bytes for either case.

@robkooper @lmarini any thoughts? This sounds like it might be one or more new tickets, but curious what you think

**Comment by robkooper** [comment]
I think it is ok to just add maybe a text file called `error.txt` with text "file is archived" or "file is not ready for download".

**Review by lmarini — APPROVED** [review]

**Pull request merged**
