### PR TITLE
Add support for Amplitude clickstream/tracking

### PR DESCRIPTION
**Pull request by bodom0015**
## Description
Add support for Admin to specify Amplitude apikey for tracking/analytics

## Review Time Estimate

- [ ] Immediately
- [x] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by robkooper** [comment]
will this PR eventually contain the actual tracking code, or will that come in a different PR?

**Comment by bodom0015** [comment]
Question asked and answered 😆 

Supplementary PR that contains the actual event code, which may require a bit more discussion: https://github.com/clowder-framework/clowder/pull/133

I'm hoping that this one will be a quicker merge while we discuss the actual events themselves

**Comment by robkooper** [comment]
Question. Would it make sense to have a small javascript file that gets included on the main page. This javascript file will have 3 pieces:
- initalize the code based on what api keys are set (google, amplitude, others), will be always loaded
- page load event, send a page load to each service enabled, will be always loaded
- logevent(code, parameters), an explicit function that can call all of the serviecs. right now it will just implement the clickstream. 

The thinking is that if we add additional trackers, we can just update this one javascript file and it will support a new service.

**Comment by lmarini** [comment]
> Question. Would it make sense to have a small javascript file that gets included on the main page. This javascript file will have 3 pieces:
> 
> * initalize the code based on what api keys are set (google, amplitude, others), will be always loaded
> * page load event, send a page load to each service enabled, will be always loaded
> * logevent(code, parameters), an explicit function that can call all of the serviecs. right now it will just implement the clickstream.
> 
> The thinking is that if we add additional trackers, we can just update this one javascript file and it will support a new service.

In the developer meeting today we discussed doing this at a later date

**Review by lmarini — CHANGES_REQUESTED** [review]
Was able to test it with the live service. @bodom0015 can you please add to CHANGELOG before we merge? Thank you.

**Review by lmarini — APPROVED** [review]

**Pull request merged**
