### PR TITLE
386 datasetlastmodifieddate is not updated

### PR DESCRIPTION
**Pull request by ddey2**
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [x] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tcnichol** [comment]
I pushed a small change. I was getting some errors but they were small fixes.

I have tried adding files and deleting them, but it doesn't seem my dataset is showing the lastUpdated time changing. Will delete this db and start over and try again.

**Comment by ddey2** [comment]
@tcnichol Thanks, I am looking into this.

**Comment by tcnichol** [comment]
I made one commit - in datasets.submit i added the same update of the time you had elsewhere. I think that catches it when files are uploaded through the web interface and not the API and will now update the last modified time.

**Comment by ddey2** [comment]
Adding last modified date to UI

Screen Shot 2022-11-16 at 2 56 31 PM

**Review by robkooper — APPROVED** [review]

**Pull request merged**
