### PR TITLE
Fix to incorrect sorting for default cases

### PR DESCRIPTION
**Pull request by ddey2**
Signed-off-by: Dipannita Dey <ddey2@illinois.edu>

## Description
#248 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the CHANGELOG.md.
- [x] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by robkooper — CHANGES_REQUESTED** [review]
Can you update the changelog, add a link the issue #248

**Comment by ddey2** [comment]
> Can you update the changelog, add a link the issue #248

I added the link in description. Does that look good?

**Review by robkooper — COMMENTED** [review]
please add yourself to contributors.md file

**Review by lmarini — APPROVED** [review]
Works great! Next time you can create the branch in the repository and make the PR from there. You don't have to fork if you don't want to. Thank you.

**Review by lmarini — APPROVED** [review]

**Pull request merged**
