### PR TITLE
266 add when parameter in api datasets, collections and spaces

### PR DESCRIPTION
**Pull request by longshuicy**
## Description
add "when" parameter in below endpoints:
```
GET /api/datasets
GET /api/datasets/canEdit

GET /api/collections
GET /api/collections/canEdit  
GET /api/collections/possibleParents
GET /api/collections/{coll_id}/datasetPossibleParents/{ds_id}
GET /api/collections/list 

GET /api/spaces
GET /api/spaces/canEdit
```
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bodom0015** [comment]
@longshuicy so it looks like the `when` parameter can take either "a" (after) or "b" (before) as a value, is that right? Do you happen to have any examples of a few queries that are expected to succeed?

@robkooper @lmarini I'm also having trouble figuring out the correct format for the `date` parameter. Looking through the code, shouldn't this be an ISO 8601-like timestamp?

 Would recommend adding the related parameters to `public/swagger.yaml` to simplify testing the new API endpoints:
```yaml
      parameters:
        - name: when
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
```

**Comment by robkooper** [comment]
@bodom0015 thanks for catching the swagger docs update.

**Comment by longshuicy** [comment]
@bodom0015 
yes, it takes either a (after) or b (before). but only "a" is enforced, other characters even though it's not "b" is counted as nextPage = false.

I copied that logic from the controller methods. e.g. GET /datasets --> 
```
def list(when: String, date: String, limit: Int, space: Option[String], status: Option[String], mode: String, owner: Option[String], showPublic: Boolean, showOnlyShared : Boolean, showTrash : Boolean) = UserAction(needActive=false) { implicit request =>
    implicit val user = request.user

    val nextPage = (when == "a")
    val person = owner.flatMap(o => users.get(UUID(o)))
    val ownerName = person match {
      case Some(p) => Some(p.fullName)
      case None => None
    }
...
...
```

**Comment by longshuicy** [comment]
@bodom0015 here is what i use to test
http://localhost:9000/api/datasets?superAdmin=true&limit=3&when=b&date=2021-07-28T16:24:49.000Z
hmm you might be missing a Z in the end

**Comment by longshuicy** [comment]
updated the swagger. Thanks! @bodom0015

**Comment by lmarini** [comment]
please update changelog

**Review by bodom0015 — APPROVED** [review]
@longshuicy thank you, the missing Z was indeed the problem there!

I think my confusion here was that the milliseconds **and** timezone are both required.

For example, despite them all describing the same epoch moment:
* Invalid: `2021-05-31T16:33:54+00:00` and `2021-05-31T16:33:54Z` 
* Valid: `2021-05-31T16:33:54.000+00:00` and `2021-05-31T16:33:54.000Z`

Either way, the format stuff is outside of the scope of this PR! :+1: LGTM

**Review by max-zilla — APPROVED** [review]

**Pull request merged**
