### PR TITLE
Added GLTF loading capabilities to viewer_three.js previewer as well as a loading screen

### PR DESCRIPTION
**Pull request by cconsta1**
## Description

- Added the ability to load GLTF files
- Fixed positioning issues with the 3D model
- Added a loading screen

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [x] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by robkooper** [comment]
looks like you deleted .gitignore as well as the docker-compose files, can you undo those changes please.

**Comment by cconsta1** [comment]
> looks like you deleted .gitignore as well as the docker-compose files, can you undo those changes please.

Hi @robkooper! I think I reverted the files following @lmarini instructions. Can you check, please? If not I'll delete this pull request and start over. Thanks for checking!

**Comment by lmarini** [comment]
Hi @cconsta1 will you be making a new PR with this work?

**Comment by cconsta1** [comment]
Hi Luigi! Yes. It’ll combine some improvements of the GLTF previewer and the new IFC previewer :)

**Pull request closed without merging**
